version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
        - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=katekopylova
      - POSTGRES_PASSWORD=08041994Katrin


