version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: katekopylova
      POSTGRES_PASSWORD: 08041994Katrin

      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql